FROM python:3.9

WORKDIR /app

COPY ./data ./data
COPY generator.py generator.py
COPY infrastracture.py infrastracture.py
COPY main.py main.py
COPY prep_data.py prep_data.py
COPY unmask_model.py unmask_model.py

RUN pip install --upgrade pip
RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
RUN pip install pyarrow numpy pandas accelerate datasets Flask huggingface-hub nltk openpyxl python-dotenv tokenizers transformers
RUN pip install telebot

CMD ["python", "./main.py"]

EXPOSE 80:80